use super::*;
use crate::{
    Land,
    all::ForestKind,
    site::util::sprites::PainterSpriteExt,
    util::{DIRS, RandomField, Sampler},
};
use common::{
    calendar::{Calendar, CalendarEvent},
    terrain::{Block, BlockKind, SpriteKind},
};
use rand::{prelude::*, seq::IndexedRandom};
use strum::IntoEnumIterator;
use vek::*;

/// Represents house data generated by the `generate()` method
pub struct Building {
    /// Tile position of the door tile
    pub door_tile: Vec2<i32>,
    /// Axis aligned bounding region of tiles
    tile_aabr: Aabr<i32>,
    /// Axis aligned bounding region for the house
    bounds: Aabr<i32>,
    /// Approximate altitude of the door tile
    pub(crate) alt: i32,
}

impl Building {
    pub fn generate(
        land: &Land,
        rng: &mut impl Rng,
        site: &Site,
        door_tile: Vec2<i32>,
        door_dir: Vec2<i32>,
        tile_aabr: Aabr<i32>,
        calendar: Option<&Calendar>,
        alt: Option<i32>,
    ) -> Self {
        Self {
            door_tile,
            tile_aabr,
            bounds: Aabr {
                min: site.tile_wpos(tile_aabr.min),
                max: site.tile_wpos(tile_aabr.max),
            },
            alt: alt.unwrap_or_else(|| {
                land.get_alt_approx(site.tile_center_wpos(door_tile + door_dir)) as i32
            }),
        }
    }
}

impl Structure for Building {
    #[cfg(feature = "dyn-lib")]
    #[unsafe(export_name = "as_dyn_structure_building")]
    fn as_dyn_outer(&self) -> Option<(&dyn Structure, &'static str)> {
        Some((Self::as_dyn_impl(self), "as_dyn_structure_building"))
    }

    fn spawn_rules_inner(
        &self,
        spawn_rules: &mut SpawnRules,
        _land: &Land,
        _wpos: Vec2<i32>,
        weight: f32,
    ) {
        spawn_rules.prefer_alt(self.alt as f32, weight * 1.0);
    }

    fn render_inner(&self, site: &Site, _land: &Land, painter: &Painter) {
        painter
            .aabb(Aabb {
                min: site.tile_wpos(self.tile_aabr.min).with_z(self.alt),
                max: site.tile_wpos(self.tile_aabr.max).with_z(self.alt + 14),
            })
            .fill(Fill::Block(Block::new(
                BlockKind::Wood,
                Rgb::new(100, 100, 100),
            )));
    }
}
